// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASIGHv4okR0fCJMK8ZkO8NHEYuyEeB3iI',
    appId: '1:623060896760:web:793ea525f6e231a08da40d',
    messagingSenderId: '623060896760',
    projectId: 'para-recommand-app',
    authDomain: 'para-recommand-app.firebaseapp.com',
    storageBucket: 'para-recommand-app.appspot.com',
    measurementId: 'G-XG60GT9X9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRzqQTri8-663T0T8enauEXe_UC6TzBec',
    appId: '1:623060896760:android:54206a5cfb6cb3f48da40d',
    messagingSenderId: '623060896760',
    projectId: 'para-recommand-app',
    storageBucket: 'para-recommand-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo4COSE5FiuItDIgm5fS3VmcWXEhh7-sU',
    appId: '1:623060896760:ios:6d9d582174d181e78da40d',
    messagingSenderId: '623060896760',
    projectId: 'para-recommand-app',
    storageBucket: 'para-recommand-app.appspot.com',
    iosBundleId: 'com.example.paraRecommandApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCo4COSE5FiuItDIgm5fS3VmcWXEhh7-sU',
    appId: '1:623060896760:ios:6d9d582174d181e78da40d',
    messagingSenderId: '623060896760',
    projectId: 'para-recommand-app',
    storageBucket: 'para-recommand-app.appspot.com',
    iosBundleId: 'com.example.paraRecommandApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASIGHv4okR0fCJMK8ZkO8NHEYuyEeB3iI',
    appId: '1:623060896760:web:a68b939daaa43a6a8da40d',
    messagingSenderId: '623060896760',
    projectId: 'para-recommand-app',
    authDomain: 'para-recommand-app.firebaseapp.com',
    storageBucket: 'para-recommand-app.appspot.com',
    measurementId: 'G-DXB7F6DBDG',
  );
}
